services:
  backend:
    ports:
     - "5000:5000"
     - "5001:5001"
    image: transcribe_server:latest
    volumes:
      - back:/persistent
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia #ONLY Nvidia will work when using docker-compose
              count: 1
              capabilities: [gpu]
volumes:
    back:
